### ISSUE TITLE
.github: docker build refactor

### ISSUE THREAD

**Issue by MSevey** [celestiaorg/celestia-app#886] opened 2022-10-19 14:27 UTC
[non blocking][questions]
can we create an issue for this? I don't think the ephemeral cluster is using the docker builds as we just added in #881 and #882, should they be using the same? ref https://github.com/celestiaorg/.github/pull/4

The ones we just added should build when pushing matching tags, so I don't think we have to do anything there. 

possibly stupid question, will we be using this https://github.com/celestiaorg/.github/blob/main/.github/actions/docker-publish/action.yml ?

_Originally posted by @evan-forbes in https://github.com/celestiaorg/celestia-app/pull/884#discussion_r998830094_

**Comment by rootulp** [comment] 2024-01-21 05:37
I see this was a follow-up from a PR but I don't really understand what we need to do to close this issue. Can someone clarify what the problem is and how to fix it?

**Comment by rootulp** [comment] 2024-04-01 15:43
cc: @MSevey please re-open with more details if we still need to do this.

**Closed by rootulp** 2024-04-01 15:43 UTC
