### ISSUE TITLE
Revert using a commit in the `MajorUpgradeToV3`

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3981] opened 2024-10-16 13:54 UTC
LGTM

Can we just create a follow up issue to fix the v3 upgrade test such that we don't need a fixed commit tag

_Originally posted by @cmwaters in https://github.com/celestiaorg/celestia-app/pull/3882#pullrequestreview-2372557757_

**Comment by rootulp** [comment] 2024-10-16 14:26
Can close this as a duplicate of https://github.com/celestiaorg/celestia-app/issues/3947

**Closed by rootulp** 2024-10-16 14:26 UTC
Labels: WS: Maintenance 🔧, nice to have, WS: V3 3️⃣, flup
