### ISSUE TITLE
tx not found

### ISSUE THREAD

**Issue by hot-westeros** [celestiaorg/celestia-app#2806] opened 2023-11-02 12:03 UTC
### Summary of Bug

Hi, After testing, we found that there are many txs not found, such as the hash ba68a0fbb70b062f1a3452dda918c75cddbdb2bdc8f7eb34ee91d42e8e505326. Our wallet program decoded and detected this transaction, but could not obtain the detailed information.

curl -X 'GET' 'https://api.celestia.pops.one/cosmos/tx/v1beta1/txs/ba68a0fbb70b062f1a3452dda918c75cddbdb2bdc8f7eb34ee91d42e8e505326'
{
  "code": 5,
  "message": "tx not found: ba68a0fbb70b062f1a3452dda918c75cddbdb2bdc8f7eb34ee91d42e8e505326",
  "details": [
  ]
}

What causes this transaction? Is it a special transaction? Can your team help to check it? Thanks!

### Version

v1.3.0

### Steps to Reproduce

1. Get the data of block height 408
curl https://api.celestia.pops.one/cosmos/base/tendermint/v1beta1/blocks/408
2. Use program decoding to obtain the transaction list
ba68a0fbb70b062f1a3452dda918c75cddbdb2bdc8f7eb34ee91d42e8e505326 in block
3. Report an error after obtaining transaction details
curl -X 'GET' 'https://api.celestia.pops.one/cosmos/tx/v1beta1/txs/ba68a0fbb70b062f1a3452dda918c75cddbdb2bdc8f7eb34ee91d42e8e505326'
{
   "code": 5,
   "message": "tx not found: ba68a0fbb70b062f1a3452dda918c75cddbdb2bdc8f7eb34ee91d42e8e505326",
   "details": [
   ]
}

### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment] 2023-11-06 11:59
Can you please elaborate on

> Use program decoding to obtain the transaction list

https://www.mintscan.io/celestia/block/408 contains 100 txs but I can't find the tx hash you pasted. For example https://www.mintscan.io/celestia/tx/ba68a0fbb70b062f1a3452dda918c75cddbdb2bdc8f7eb34ee91d42e8e505326?height=408 does not display a result.

**Comment by hot-westeros** [comment] 2023-11-06 13:07
Use program decoding to obtain the transaction list --- You can find a Cosmos SDK to parse out the transactions contained in block 408.

Yes, that's the problem, the transaction cannot be found on the node and block explorer. But the txs field in the block 408 information contains the transaction hash.

**Comment by rootulp** [comment] 2023-11-06 13:38
Sorry to repeat this but can you please expand on

> You can find a Cosmos SDK to parse out the transactions contained in block 408.

I'm not convinced that the tx hash in the issue description actually exists in block 408 so I think the mechanism you're using to parse out the transaction hashes is flawed. Can you link to the code you're using or a Go playground that reproduces it?

**Comment by hot-westeros** [comment] 2023-11-06 13:47
> Sorry to repeat this but can you please expand on
> 
> > You can find a Cosmos SDK to parse out the transactions contained in block 408.
> 
> I'm not convinced that the tx hash in the issue description actually exists in block 408 so I think the mechanism you're using to parse out the transaction hashes is flawed. Can you link to the code you're using or a Go playground that reproduces it?

Sorry, I'm busy today. Tomorrow I will use a test code to completely reproduce the issue. Thank you for your reply and your patience.

**Comment by hot-westeros** [comment] 2023-11-07 14:10
package main

import (
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
)

type BlockResponse struct {
	Block Block `json:"block"`
}

type Block struct {
	Data BlockData `json:"data"`
}

type BlockData struct {
	Txs []string `json:"txs"`
}

func sum(bz []byte) []byte {
	h := sha256.Sum256(bz)
	return h[:]
}

func main() {
	blockHeight := 408
	apiURL := fmt.Sprintf("https://api.celestia.pops.one/cosmos/base/tendermint/v1beta1/blocks/%d", blockHeight)

	response, err := http.Get(apiURL)
	if err != nil {
		fmt.Println("Unable to get block data:", err)
		return
	}
	defer response.Body.Close()

	var blockResponse BlockResponse
	if err := json.NewDecoder(response.Body).Decode(&blockResponse); err != nil {
		fmt.Println("Unable to parse block data:", err)
		return
	}

	fmt.Println("block height:", blockHeight)
	txCount := 0

	for _, rawTx := range blockResponse.Block.Data.Txs {
		txCount++
		fmt.Println("Transaction #", txCount)
		fmt.Println("rawTx:", rawTx)
		txBytes, err := base64.StdEncoding.DecodeString(rawTx)
		if err != nil {
			fmt.Println(err)
			return
		}
		txHash := hex.EncodeToString(sum(txBytes))

		fmt.Println("txHash (lowercase):", txHash)
		fmt.Println("txHash (uppercase):", strings.ToUpper(txHash))
		fmt.Println()
	}
}

**Comment by hot-westeros** [comment] 2023-11-07 14:14
The above is the golang test code. You can see the results by running it locally. Since the log is too long, I didn't upload it.

You can see that the last transaction parsed out is:
txHash (lowercase): ba68a0fbb70b062f1a3452dda918c75cddbdb2bdc8f7eb34ee91d42e8e505326
txHash (uppercase): BA68A0FBB70B062F1A3452DDA918C75CDDBDB2BDC8F7EB34EE91D42E8E505326

But via curl -X 'GET' 'https://api.celestia.pops.one/cosmos/tx/v1beta1/txs/ba68a0fbb70b062f1a3452dda918c75cddbdb2bdc8f7eb34ee91d42e8e505326'
Obtained in this way, the returned message is tx not found.

**Comment by evan-forbes** [comment] 2023-11-07 14:57
the transactions found in the comet block are encoded as protobuf encoded `BlobTx`, which contains both the blob and the transaction that pays for that blob. The hashes stored and returned by comet (for example when I submit a tx) have been modified to only represent the transaction that the user signs over, not the `BlobTx`. More information can be found in our in various portions of our [spec](https://github.com/celestiaorg/celestia-app/blob/main/x/blob/README.md#abstract), but I can see how this has not been communicated clearly enough.

if we are only interested in the transactions, then we can use the encoding config to decode transactions in golang. The canonical way of getting blobs is from celestia-node, but if we're also interested in the blob then we can parse BlobTxs in this [functions](https://github.com/celestiaorg/celestia-app/blob/7e9fb84642dde8d51853e73efb817bf8067ffc7f/pkg/blob/blob.go#L56-L76). After parsing the blobtx, then we simply hash the tx in the `Tx` field and get the actual hash.

**Comment by evan-forbes** [comment] 2023-11-12 19:33
@hot-westeros does this make sense? have any further questions? I (and our docs) might not be explaining it well enough

I would like to close this issue since it is not a bug, although it has been very valuable feedback for improving devX

**Comment by hot-westeros** [comment] 2023-11-13 08:30
OK, you can close, thanks for your follow-up and reply.

**Closed** 2023-11-13 08:39 UTC
Labels: bug, external

**Comment by rootulp** [comment] 2023-12-15 03:54
Sorry I'm late to this but if it's helpful, I modified your code snippet and pasted https://go.dev/play/p/89hzCtbwrY3. When I run it, I observe the last tx hash as:

```go
tx 273
txHash: C55BDD3DF3348A9F8D9206528051804754F009A1B9D0F69CCC2F9D4334215D21
```

which is available at https://api.celestia.pops.one/cosmos/tx/v1beta1/txs/C55BDD3DF3348A9F8D9206528051804754F009A1B9D0F69CCC2F9D4334215D21. The major difference between your code and the revised code in my Go playground is the `getTxBytes` behavior.
