### ISSUE TITLE
Celestia-appd is unavailable on MacOS

### ISSUE THREAD

**Issue by 0xyicheng** [celestiaorg/celestia-app#375] opened 2022-04-29 14:33 UTC
# Summary of Bug

While attempting to install the celestia-app, the following error was thrown:

`--> Installing celestia-appd
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here`

`ld: warning: object file (/var/folders/m0/jrc1xkhd62l_y5vj5d203cfw0000gn/T/go-link-556648135/000000.o) was built for newer macOS version (11.1) than being linked (11.0)
ld: warning: object file (/var/folders/m0/jrc1xkhd62l_y5vj5d203cfw0000gn/T/go-link-556648135/000001.o) was built for newer macOS version (11.1) than being linked (11.0)......
`

Then run `celestia-appd init test --chain-id test`
got： `command not found: celestia-appd`

# Version
commit=07816a7f1ef0a45d5b189b279bc85ce75fc4be14

# Steps to Reproduce

````
gh repo clone celestiaorg/celestia-app 
make install  
celestia-appd init test --chain-id test
````

**Comment by liamsi** [comment] 2022-05-02 08:51
I also use macOS and I can't reproduce the linker issue. It seems this is specific to your environment or how brew installs golang. See this issue for reference please: https://github.com/golang/go/issues/43856

**Comment by liamsi** [comment] 2022-05-14 13:21
Can we close this?

**Closed** 2022-07-06 12:33 UTC

**Comment by rootulp** [comment] 2022-07-11 19:58
I'm also observing this error:

```
$ make install
--> Ensure dependencies have not been modified
GO111MODULE=on go mod verify
all modules verified
--> Installing celestia-appd
# github.com/keybase/go-keychain
cgo-gcc-prolog:81:11: warning: 'SecKeychainCreate' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:301:10: note: 'SecKeychainCreate' has been explicitly marked deprecated here
cgo-gcc-prolog:139:11: warning: 'SecKeychainLock' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:357:10: note: 'SecKeychainLock' has been explicitly marked deprecated here
cgo-gcc-prolog:159:11: warning: 'SecKeychainOpen' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:287:10: note: 'SecKeychainOpen' has been explicitly marked deprecated here
cgo-gcc-prolog:183:11: warning: 'SecKeychainUnlock' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:347:10: note: 'SecKeychainUnlock' has been explicitly marked deprecated here
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
```

OS: macOS Monterey Version 12.4
Chip: Apple M1 Pro

I recall installing XCode Command Line Tools directly via `xcode-select --install`. 
```shell
xcode-select --print-path
/Library/Developer/CommandLineTools
```
