### ISSUE TITLE
Test the prebuilt binaries

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2737] opened 2023-10-20 13:28 UTC
The prebuilt binaries were/are not working, so we should have tests that can detect this. Ideally these tests would include 

- using a mock ledger
- running the same prebuilt on all of the supported versions/distros
- start a single validator network

**Comment by rootulp** [comment] 2023-10-20 14:26
A prerequisite to this issue is defining all supported versions / architectures / distributions

**Comment by evan-forbes** [comment] 2023-10-20 14:41
I'm good with just the existing ubuntu and mac latest just to get the infrastructure up, and then we can add others. Would love to support the latest arch, nix, and bsd eventually

**Comment by rootulp** [comment] 2023-10-20 18:25
Created https://github.com/celestiaorg/celestia-app/issues/2742 which we should tackle before this issue

**Comment by rootulp** [comment] 2023-12-15 00:31
I agree with the motivation for this issue but closing b/c we discussed in person that it currently isn't worth investing in testing Ledger support on the pre-built binaries because the proposed mechanisms to do so: mock Ledger aren't as reliable as literally testing with a real Ledger.

It's far from ideal but we currently get signal from users if Ledger stops working on a prebuilt binary. We have a dedicated test to make sure that celestia-app can build with Ledger support (doesn't cover pre-built binaries) but that has already caught a few regressions.

**Closed by rootulp** 2023-12-15 00:31 UTC
Labels: CI
