### ISSUE TITLE
PayForData Tx included in many blocks

### ISSUE THREAD

**Issue by lzrscg** [celestiaorg/celestia-app#465] opened 2022-06-04 06:27 UTC
## Summary of Bug

The same failed pfd tx is included in many blocks. 

See next comment for list of affected blocks (according to my indexer's db)

My total count as of the time of writing this is: 472. However, there may be more due to the way I've been indexing this.

The hash: `ED87DB3BB405F8D38ABCFCD3E6076A5542909F0F16C3D63CCC018F2D954BA8CE`
The tx (unwrapped):
```
Cn0KewoWL3BheW1lbnQuTXNnUGF5Rm9yRGF0YRJhCi9jZWxlc3RpYTFyY3Y3OXVyMHplaDA4Y3docmFraDZjcWx6ZTUwNnIyOHc1czJnMhII//////////4YkLcBIiDzRgpH86+ZDb1H1132U3mT/bqog6idcpM1f2kAqZDDZBJkClAKRgofL2Nvc21vcy5jcnlwdG8uc2VjcDI1NmsxLlB1YktleRIjCiECXAxriLymfx/SWSQlZQsSvPviH7WuyF1oHoAYrfGLjHMSBAoCCAEYARIQCgkKBHV0aWESATEQgMLXLxpAIwErvo7aVv28MnObOSt9Cak+rEdKn3alJ/J5qLnm1zJ638HRFzq4x7LD96Mc3ACE+bkcs4WAM+p4zoqI09xDFw==
```
Malleated (how it appears in the block):
```
CiDth9s7tAX404q8/NPmB2pVQpCfDxbD1jzMAY8tlUuozhKnAgp9CnsKFi9wYXltZW50Lk1zZ1BheUZvckRhdGESYQovY2VsZXN0aWExcmN2Nzl1cjB6ZWgwOGN3aHJha2g2Y3FsemU1MDZyMjh3NXMyZzISCP/////////+GJC3ASIg80YKR/OvmQ29R9dd9lN5k/26qIOonXKTNX9pAKmQw2QSZApQCkYKHy9jb3Ntb3MuY3J5cHRvLnNlY3AyNTZrMS5QdWJLZXkSIwohAlwMa4i8pn8f0lkkJWULErz74h+1rshdaB6AGK3xi4xzEgQKAggBGAESEAoJCgR1dGlhEgExEIDC1y8aQCMBK76O2lb9vDJzmzkrfQmpPqxHSp92pSfyeai55tcyet/B0Rc6uMeyw/ejHNwAhPm5HLOFgDPqeM6KiNPcQxc=
```
Decoded:
https://celestia.explorers.guru/transaction/ED87DB3BB405F8D38ABCFCD3E6076A5542909F0F16C3D63CCC018F2D954BA8CE (keep watching the block height on this tx increase, right now its 25409)

Also, I tested and this is not happening for `F7DABD37A745A32E63BEBADDEACE62FE9D37D521457B64B973C4F956D463497A`  (#456)

## Version
v0.5.2

## Steps to Reproduce
As an example, I will choose two random blocks from the below list and query public RPC:
https://rpc-mamaki.pops.one/block?height=24107
```
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "block_id": {
      "hash": "A5E3AB6CDB66225EC020B8040D6AF058467C100BA8990788F37A422D16AACC20",
      "parts": {
        "total": 1,
        "hash": "E5EA127FAEDFD86EB916D221FBDEC5848A84F87B16B3217B37D2A5A8D47F3845"
      }
    },
    "block": {
      "header": {
        "version": {
          "block": "11",
          "app": "0"
        },
        "chain_id": "mamaki",
        "height": "24107",
        "time": "2022-06-03T11:58:56.927136653Z",
        "last_block_id": {
          "hash": "18D78057388806EF69669D36978D388F9A618893E1B9CB87FE238918062F0926",
          "parts": {
            "total": 1,
            "hash": "5D25BFDC9A46D34089C6BE7AE1EDB7B244CB08516EFB9ADF3B7CC54888DD26BD"
          }
        },
        "last_commit_hash": "47DB012F58A29AA7BF17B5C34A3606976AE5F1DF8461AAD462AFD29A6929CDF5",
        "data_hash": "82FD045558C59F71678A8FDB609BD187A6D4A2DFD7846C4D0CF7EAA7EC929B6A",
        "validators_hash": "42EE553C0D59A9875C6C2E2E572E65C3C2E3E5F2D7F87B492D6230B7A24754D3",
        "next_validators_hash": "42EE553C0D59A9875C6C2E2E572E65C3C2E3E5F2D7F87B492D6230B7A24754D3",
        "consensus_hash": "048091BC7DDC283F77BFBF91D73C44DA58C3DF8A9CBC867405D8B7F3DAADA22F",
        "app_hash": "395B3644AF4E00DC4435E63BC024994D8BB3DDDC342E6A3A599D7CBD3D676A47",
        "last_results_hash": "8BEECA59F2F199959E3745C8CE72C9D0FA44E3004DA92F2EEFACA1DAB0EE3C01",
        "evidence_hash": "E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855",
        "proposer_address": "604377BC74F4F27274825A564761D9875B31AF05"
      },
      "data": {
        "txs": [
          "CiDth9s7tAX404q8/NPmB2pVQpCfDxbD1jzMAY8tlUuozhKnAgp9CnsKFi9wYXltZW50Lk1zZ1BheUZvckRhdGESYQovY2VsZXN0aWExcmN2Nzl1cjB6ZWgwOGN3aHJha2g2Y3FsemU1MDZyMjh3NXMyZzISCP/////////+GJC3ASIg80YKR/OvmQ29R9dd9lN5k/26qIOonXKTNX9pAKmQw2QSZApQCkYKHy9jb3Ntb3MuY3J5cHRvLnNlY3AyNTZrMS5QdWJLZXkSIwohAlwMa4i8pn8f0lkkJWULErz74h+1rshdaB6AGK3xi4xzEgQKAggBGAESEAoJCgR1dGlhEgExEIDC1y8aQCMBK76O2lb9vDJzmzkrfQmpPqxHSp92pSfyeai55tcyet/B0Rc6uMeyw/ejHNwAhPm5HLOFgDPqeM6KiNPcQxc=",
          "Cr8DCqQBCjcvY29zbW9zLmRpc3RyaWJ1dGlvbi52MWJldGExLk1zZ1dpdGhkcmF3RGVsZWdhdG9yUmV3YXJkEmkKL2NlbGVzdGlhMWc0dmxod3RqeW0wdDZ2cGF4cjNleXA3OG5rZWt4Z3gyZmQ0dGxyEjZjZWxlc3RpYXZhbG9wZXIxZzR2bGh3dGp5bTB0NnZwYXhyM2V5cDc4bmtla3hneDJ2amhqZjkKdwo7L2Nvc21vcy5kaXN0cmlidXRpb24udjFiZXRhMS5Nc2dXaXRoZHJhd1ZhbGlkYXRvckNvbW1pc3Npb24SOAo2Y2VsZXN0aWF2YWxvcGVyMWc0dmxod3RqeW0wdDZ2cGF4cjNleXA3OG5rZWt4Z3gydmpoamY5CpwBCiMvY29zbW9zLnN0YWtpbmcudjFiZXRhMS5Nc2dEZWxlZ2F0ZRJ1Ci9jZWxlc3RpYTFnNHZsaHd0anltMHQ2dnBheHIzZXlwNzhua2VreGd4MmZkNHRschI2Y2VsZXN0aWF2YWxvcGVyMWc0dmxod3RqeW0wdDZ2cGF4cjNleXA3OG5rZWt4Z3gydmpoamY5GgoKBHV0aWESAjE0EmQKUQpGCh8vY29zbW9zLmNyeXB0by5zZWNwMjU2azEuUHViS2V5EiMKIQLq3O5Uq1VXNfzxBXfjrFr4SMfTXrw85VGEF/iIse8Q/BIECgIIARjcBBIPCgkKBHV0aWESATAQkKEPGkBTa0YY0bFw6slUI1Y8jmD916NnKCeMi38Izzr7k4mq5xD6IMr+SYhH30IUC6wC+AuBUtGriTuermYFmdOSrQ5u",
          "CqUBCqIBCiMvY29zbW9zLnN0YWtpbmcudjFiZXRhMS5Nc2dEZWxlZ2F0ZRJ7Ci9jZWxlc3RpYTEwOW56aGY2ZnZxdmZhbjN0YXl6YzhjeXdjc2s2YTVxNDNxZTB6axI2Y2VsZXN0aWF2YWxvcGVyMTA5bnpoZjZmdnF2ZmFuM3RheXpjOGN5d2NzazZhNXE0NWxtazVzGhAKBHV0aWESCDY1MTAwMjE4ElkKUQpGCh8vY29zbW9zLmNyeXB0by5zZWNwMjU2azEuUHViS2V5EiMKIQLr2GHDKBGKFygIco+IZDcWMGicRrdRn4zq/+ifJ8TkixIECgIIARi4KRIEEMCaDBpAVj+u26u2ZqlggEQvL79ep3yBfAB9IYPp7GC/FEWPmz9HThFZ54IPwKBqnvAUPhCeRSLjw0uawUuLArYr3o3jsQ=="
        ],
        "evidence": {
          "evidence": []
        },
        "msgs": {
          "msgs": [
            {
              "NamespaceID": "//////////4=",
              "Data": "V2UgcHJv...YXNlLg=="
            }
          ]
        },
        "square_size": "16"
      },
      "last_commit": {
        "height": "24106",
        "round": 0,
        "block_id": {
          "hash": "18D78057388806EF69669D36978D388F9A618893E1B9CB87FE238918062F0926",
          "parts": {
            "total": 1,
            "hash": "5D25BFDC9A46D34089C6BE7AE1EDB7B244CB08516EFB9ADF3B7CC54888DD26BD"
          }
        },
        "signatures": [...]
      }
    }
  }
}
```

https://rpc-mamaki.pops.one/block?height=24781
```
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "block_id": {
      "hash": "767EA45A3B0B9088E25C3C07D8D94AF6C01BD72477D4F6130A4319A417742B32",
      "parts": {
        "total": 1,
        "hash": "D33DCC773BE7460FF698802BD4ACC00BF2D8F284CC1771906DC415988777972B"
      }
    },
    "block": {
      "header": {
        "version": {
          "block": "11",
          "app": "0"
        },
        "chain_id": "mamaki",
        "height": "24781",
        "time": "2022-06-03T18:51:24.959203256Z",
        "last_block_id": {
          "hash": "F09F00EE19D2F03BC778C857BFB1FB68F33B812218F917691B3B63F248BFB055",
          "parts": {
            "total": 1,
            "hash": "65C10CA2F687FE90D57D50BF7A51D44DE865615E14CD0EC7E2349D7B827D3681"
          }
        },
        "last_commit_hash": "6FD7122AD1FD5E0F1F709F353E903C63919B9E7513C4454919A37598D79AC163",
        "data_hash": "0D7E315650C39DEB20D21FDE2762999DC944573B745DEFA7AE39A8C71727D985",
        "validators_hash": "B4B6641A1F3A5F35CAF6A57679A70CF72036A62EC135B8783F82FE3D0E22DB8E",
        "next_validators_hash": "B4B6641A1F3A5F35CAF6A57679A70CF72036A62EC135B8783F82FE3D0E22DB8E",
        "consensus_hash": "048091BC7DDC283F77BFBF91D73C44DA58C3DF8A9CBC867405D8B7F3DAADA22F",
        "app_hash": "EDE438B4404ED2432A55B525928B47B24A87406ADCC7948CD410757C14036132",
        "last_results_hash": "DFA14135FB5AA0E8229F63D57FC493026618B2B470445A9A74D7722EFD8B0896",
        "evidence_hash": "E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855",
        "proposer_address": "773E2B801BA253394B2A9963C4FE8DE03566D6D2"
      },
      "data": {
        "txs": [
          "CiDth9s7tAX404q8/NPmB2pVQpCfDxbD1jzMAY8tlUuozhKnAgp9CnsKFi9wYXltZW50Lk1zZ1BheUZvckRhdGESYQovY2VsZXN0aWExcmN2Nzl1cjB6ZWgwOGN3aHJha2g2Y3FsemU1MDZyMjh3NXMyZzISCP/////////+GJC3ASIg80YKR/OvmQ29R9dd9lN5k/26qIOonXKTNX9pAKmQw2QSZApQCkYKHy9jb3Ntb3MuY3J5cHRvLnNlY3AyNTZrMS5QdWJLZXkSIwohAlwMa4i8pn8f0lkkJWULErz74h+1rshdaB6AGK3xi4xzEgQKAggBGAESEAoJCgR1dGlhEgExEIDC1y8aQCMBK76O2lb9vDJzmzkrfQmpPqxHSp92pSfyeai55tcyet/B0Rc6uMeyw/ejHNwAhPm5HLOFgDPqeM6KiNPcQxc="
        ],
        "evidence": {
          "evidence": []
        },
        "msgs": {
          "msgs": [
            {
              "NamespaceID": "//////////4=",
              "Data": "V2UgcHJv...YXNlLg=="
            }
          ]
        },
        "square_size": "16"
      },
      "last_commit": {
        "height": "24780",
        "round": 0,
        "block_id": {
          "hash": "F09F00EE19D2F03BC778C857BFB1FB68F33B812218F917691B3B63F248BFB055",
          "parts": {
            "total": 1,
            "hash": "65C10CA2F687FE90D57D50BF7A51D44DE865615E14CD0EC7E2349D7B827D3681"
          }
        },
        "signatures": [...]
      }
    }
  }
}
```
Both responses here have the same malleated tx:
```
CiDth9s7tAX404q8/NPmB2pVQpCfDxbD1jzMAY8tlUuozhKnAgp9CnsKFi9wYXltZW50Lk1zZ1BheUZvckRhdGESYQovY2VsZXN0aWExcmN2Nzl1cjB6ZWgwOGN3aHJha2g2Y3FsemU1MDZyMjh3NXMyZzISCP/////////+GJC3ASIg80YKR/OvmQ29R9dd9lN5k/26qIOonXKTNX9pAKmQw2QSZApQCkYKHy9jb3Ntb3MuY3J5cHRvLnNlY3AyNTZrMS5QdWJLZXkSIwohAlwMa4i8pn8f0lkkJWULErz74h+1rshdaB6AGK3xi4xzEgQKAggBGAESEAoJCgR1dGlhEgExEIDC1y8aQCMBK76O2lb9vDJzmzkrfQmpPqxHSp92pSfyeai55tcyet/B0Rc6uMeyw/ejHNwAhPm5HLOFgDPqeM6KiNPcQxc=
```

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by lzrscg** [comment] 2022-06-04 06:28
The transaction is included in the following blocks (at the time I last checked)
```
11820
11874
11912
11966
12140
12144
12163
12209
12249
12255
12308
12336
12353
12391
12441
12445
12459
12485
12518
12532
12548
12589
12627
12633
12646
12687
12714
12731
12744
12811
13263
13275
13365
13377
13391
13402
13408
13434
13472
13492
13520
13544
13561
13572
13607
13627
13640
13650
13657
13709
13736
13755
13799
13810
13822
13866
13888
13899
13901
13943
13963
13977
13984
14036
14078
14132
14152
14175
14242
14281
14285
14299
14326
14336
14376
14398
14422
14432
14445
14450
14457
14509
14524
14536
14557
14590
14600
14619
14639
14654
14671
14678
14727
14745
14759
14768
14772
14812
14825
14838
14867
14898
14902
14911
14917
14973
14984
15004
15036
15067
15075
15127
15140
15151
15181
15229
15234
15243
15264
15293
15314
15325
15352
15380
15396
15404
15435
15477
15490
15501
15524
15545
15575
15586
15629
15648
15671
15683
15729
15759
15768
15778
15858
15863
15872
15934
15953
15958
15967
15981
16030
16059
16086
16133
16166
16172
16176
16195
16242
16261
16280
16287
16295
16372
16378
16425
16438
16441
16455
16473
16479
16498
16516
16529
16550
16562
16568
16579
16591
16603
16612
16656
16663
16676
16742
16751
16764
16805
16838
16865
16881
16919
16942
16986
17016
17028
17046
17083
17110
17116
17126
17148
17160
17188
17198
17209
17253
17281
17298
17312
17366
17404
17416
17427
17468
17473
17499
17512
17581
17604
17619
17669
17677
17701
17712
17718
17772
17778
17818
17836
17858
17882
17886
17938
17963
17967
18040
18061
18068
18090
18156
18172
18178
18192
18224
18285
18292
18303
18318
18372
18376
18394
18468
18473
18490
18517
18569
18585
18598
18625
18664
18689
18736
18769
18793
18840
18884
18895
18927
18943
18969
18983
18999
19049
19088
19094
19141
19188
19208
19245
19256
19286
19346
19362
19423
19459
19494
19528
19554
19577
19647
19655
19679
19724
19755
19768
19811
19870
19897
19925
19931
19972
20000
20080
20084
20096
20119
20177
20212
20216
20232
20286
20301
20326
20357
20385
20413
20427
20447
20511
20528
20558
20592
20616
20633
20671
20692
20734
20746
20786
20829
20834
20875
20919
20926
20951
21005
21056
21060
21096
21160
21208
21226
21260
21270
21273
21311
21326
21348
21361
21392
21413
21455
21463
21530
21569
21581
21627
21670
21684
21700
21732
21765
21768
21772
21801
21811
21833
21890
21907
21932
21971
22002
22009
22028
22074
22110
22149
22172
22198
22244
22265
22281
22341
22362
22369
22386
22434
22459
22483
22496
22541
22589
22612
22657
22672
22691
22739
22805
22829
22845
22896
22914
22934
23024
23035
23096
23125
23136
23176
23193
23243
23254
23258
23327
23361
23374
23390
23460
23485
23496
23512
23562
23585
23614
23624
23674
23702
23720
23735
23761
23781
23831
23866
23879
23919
23947
24013
24032
24037
24049
24085
24107
24129
24184
24228
24236
24252
24280
24309
24321
24366
24377
24384
24402
24408
24453
24475
24512
24567
24575
24624
24699
24728
24781
24794
24838
24871
24900
24923
24928
24986
```

**Comment by evan-forbes** [comment] 2022-06-15 03:16
Weirdly enough, it looks like some block producers are creating blocks with this PfD tx much more often than others, but still not all the time. Running a quick script that searches for this tx in all blocks height 30,000 and up, we find (map[block producer: number of blocks produced with bad pfd tx)

map[Brightlystake:1 ChainodeTech:107 NakoTurk:19 Nodes.Guru:52 P-OPS Team Validator:3 Qubelabs:90 StakeSquid:63 binary_holdings:108 pomifer:3 stakewithjenni.com:39]

this could be for a variety of reasons and needs further analysis, but I thought it was interesting none the less. 

Its possible that this is related to https://github.com/celestiaorg/celestia-core/issues/584

**Comment by evan-forbes** [comment] 2022-06-17 00:27
@lzrscg sorry for the delay on this. My first gut feeling was that this was a bug particular to mamaki, even tho I knew that this could happen on any network that uses deferred execution. Thinking on it more, while maybe not as prominent on other networks, this certainly could be an issue. Due to tendermint's current deferred execution model, txs can be included in multiple blocks. The tx could also be valid in one of the blocks that its included in as well, so no matter the cause of this particular issue, I think this is an edge case that has to be handled by block indexers/explorers. 

the only thing stopping validators from including repeat invalid txs in their blocks is the mempool cache, which by default is not on for invalid txs. 

even if nodes do have this setting configured, if they restart, then the cache is also reset. Many nodes have been restarting on mamaki frequently, so this, along with the configuration, might also explain the above comment where certian validators included this in their blocks much more often than others. I suspect that this tx, along with other invalid ones, have been continually gossiped from node node for the history of mamaki, occasionally being included in blocks when it makes it past the cache of a validator.

**Comment by evan-forbes** [comment] 2022-08-05 14:57
we might have to reopen this, but I'm closing this for now as we've downgraded to tendermint v0.34.20

**Closed by evan-forbes** 2022-08-05 14:57 UTC
Labels: bug
