### ISSUE TITLE
Enable interchaintest in CI

### ISSUE THREAD

**Issue by ninabarbakadze** [celestiaorg/celestia-app#3563] opened 2024-06-14 11:44 UTC
## Description

Currently interchaintest is not working in the CI, because go test will only run tests for the current module plus sub-packages. Interchaintest is a separate module so it needs to be run separately.

## Acceptance Criteria

- [ ] Enable those tests in the CI

**Comment by rootulp** [comment] 2024-06-14 14:45
Duplicate of https://github.com/celestiaorg/celestia-app/issues/3358

**Closed by rootulp** 2024-06-14 14:45 UTC
Labels: WS: Maintenance 🔧, WS: V2 ✌️
