### ISSUE TITLE
Celestia-appd export is panicking after export command

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-app#401] opened 2022-05-12 11:21 UTC
## Summary of Bug
After using command `celestia-appd export`, our app is panicking due to UnmarshalJSON error 

## Version
d255f0ce461e8cc72f48282593a876cca9cb6c91

## Steps to Reproduce
1. Init the app
2. Add key with backend test
3. Add genesis account 
4. Gentx
5. Collect-gentx
6. Export

Note: I've tried exporting after step 3. Then after 4/5 - the same result(panic)
```sh
 celestia-appd export                                                                                                                                                                                              bidon4@MacBook-Pro-8
panic: UnmarshalJSON cannot decode empty bytes

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get({{0x5af1c78, 0xc000ffe810}, 0xc00060ee90, {0x5a9cd40, 0xc000f02840}, {0x5a9cd90, 0xc000f02920}, {0xc0000be3e0, 0x4, 0x1a}, ...}, ...)
	/Users/bidon4/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.0.1-sdk-v0.44.2/x/params/types/subspace.go:109 +0x319
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.GetParamSet({{0x5af1c78, 0xc000ffe810}, 0xc00060ee90, {0x5a9cd40, 0xc000f02840}, {0x5a9cd90, 0xc000f02920}, {0xc0000be3e0, 0x4, 0x1a}, ...}, ...)
	/Users/bidon4/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.0.1-sdk-v0.44.2/x/params/types/subspace.go:222 +0x145
github.com/cosmos/cosmos-sdk/x/auth/keeper.AccountKeeper.GetParams(...)
	/Users/bidon4/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.0.1-sdk-v0.44.2/x/auth/keeper/params.go:15
github.com/cosmos/cosmos-sdk/x/auth.ExportGenesis({{0x5accda8, 0xc00011e008}, {0x5af6cc0, 0xc0002371c0}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, ...}, ...}, ...}, ...)
	/Users/bidon4/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.0.1-sdk-v0.44.2/x/auth/genesis.go:32 +0x125
github.com/cosmos/cosmos-sdk/x/auth.AppModule.ExportGenesis({{}, {{0x5a9cd40, 0xc000f027d0}, {0x5af1c78, 0xc000ffe810}, {{0x5af1c78, 0xc000ffe810}, 0xc00060ee90, {0x5a9cd40, 0xc000f02840}, ...}, ...}, ...}, ...)
	/Users/bidon4/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.0.1-sdk-v0.44.2/x/auth/module.go:151 +0xb8
github.com/cosmos/cosmos-sdk/types/module.(*Manager).ExportGenesis(_, {{0x5accda8, 0xc00011e008}, {0x5af6cc0, 0xc0002371c0}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, ...}, ...}, ...)
	/Users/bidon4/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.0.1-sdk-v0.44.2/types/module/module.go:328 +0x125
github.com/celestiaorg/celestia-app/app.(*App).ExportAppStateAndValidators(0xc000648000, 0x0, {0x694de20, 0x0, 0x0})
	/Users/bidon4/go/src/github.com/celestiaorg/lazyledger-app/app/export.go:33 +0x20f
github.com/tendermint/spm/cosmoscmd.appCreator.appExport({{{0x5ad5ba8, 0xc00012b5f0}, {0x5afbeb8, 0xc000ffe810}, {0x5ae6cd8, 0xc000dfd440}, 0xc00060ee90}, 0x58aac60}, {0x5acda90, 0xc001245bc0}, ...)
	/Users/bidon4/go/pkg/mod/github.com/tendermint/spm@v0.1.9/cosmoscmd/root.go:409 +0x255
github.com/cosmos/cosmos-sdk/server.ExportCmd.func1(0xc001200280, {0x694de20, 0x0, 0x0})
	/Users/bidon4/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.0.1-sdk-v0.44.2/server/export.go:71 +0x31c
github.com/spf13/cobra.(*Command).execute(0xc001200280, {0x694de20, 0x0, 0x0})
	/Users/bidon4/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000f6cc80)
	/Users/bidon4/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/bidon4/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/bidon4/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x58aac60, {0xc000f69c00, 0x1b})
	/Users/bidon4/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.0.1-sdk-v0.44.2/server/cmd/execute.go:36 +0x1eb
main.main()
	/Users/bidon4/go/src/github.com/celestiaorg/lazyledger-app/cmd/celestia-appd/main.go:26 +0x7d
```
---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Bidon15** [comment] 2022-05-12 11:21
I will try to repro on linux, but doubt that this is osx specific bug

**Comment by evan-forbes** [comment] 2022-05-12 12:30
yeah, I don't think its a mac thing, we've just never used the export functionality before. It has probably never worked tbh. This might be fixed in #399 but I'll check this out after the testnet dry run

**Comment by Bidon15** [comment] 2022-05-12 13:25
> Is the export sub-command needed for testnet? Or for setting up a testbed or sth?

Well, this commands just gives you the genesis in a more convenient way comparing to finding genesis in config -> ctrl+c / ctrl+v

https://github.com/cosmos/cosmos-sdk/blob/main/server/export.go

**Comment by evan-forbes** [comment] 2022-05-12 19:52
wait, @Bidon15 I think the issue is that the chain isn't started. If you start the chain first, then export works for me. I'm not sure that the export command is expected to work without starting it, as you should use the genesis file at that point. 

> Well, this commands just gives you the genesis in a more convenient way comparing to finding genesis in config -> ctrl+c / ctrl+v

Are you just trying to load the genesis file into the standard output? perhaps some more context with what is trying to be accomplished would help resolve the issue

**Comment by Bidon15** [comment] 2022-05-13 10:55
> wait, @Bidon15 I think the issue is that the chain isn't started. If you start the chain first, then export works for me. I'm not sure that the export command is expected to work without starting it, as you should use the genesis file at that point.

It will be very weird to assume that export won't work by design if the chain is not started/set up. Genesis is created after you init the chain(no gentx), so it is expected to work at any stage upon the first start (from ux pov as well as code is not properly pointing that the chain should be started first - correct me if I'm wrong 😅 )

> 
> > Well, this commands just gives you the genesis in a more convenient way comparing to finding genesis in config -> ctrl+c / ctrl+v
> 
> Are you just trying to load the genesis file into the standard output? perhaps some more context with what is trying to be accomplished would help resolve the issue

Yes, I've tried to use the standard output, which is causing the panic. In addition, I tried triggering the export through code and failed, too (this approach might be wrongly done from my side, so take it with a grant of salt)

**Comment by evan-forbes** [comment] 2022-05-13 12:06
> It will be very weird to assume that export won't work by design if the chain is not started/set up. Genesis is created after you init the chain(no gentx), so it is expected to work at any stage upon the first start (from ux pov as well as code is not properly pointing that the chain should be started first - correct me if I'm wrong sweat_smile )

I'm not sure I follow. Why should it be weird? If the chain isn't started, then there is no state. If there is no state, then what is the export command supposed to export? This explains the panic message, where the decoder doesn't know how to decode empty bytes.

> Yes, I've tried to use the standard output, which is causing the panic.

can you point me to some code where this is being done? I'm guessing you tried the obvious of `cat ~/.celestia-app/config/genesis.json` ?

We should also be able to load the genesis file in process if we know the path

**Comment by Bidon15** [comment] 2022-05-16 10:05
> I'm not sure I follow. Why should it be weird? If the chain isn't started, then there is no state. If there is no state, then what is the export command supposed to export? This explains the panic message, where the decoder doesn't know how to decode empty bytes.

It is weird as the export genesis is following up on gen accounts, which we have created during gentx/collect-gentx(like we should have the state, shouldn't we?) and not explicitly looking into either the chain is started or not. 

https://docs.cosmos.network/master/building-modules/genesis.html#exportgenesis

**Comment by evan-forbes** [comment] 2022-05-16 14:48
> It is weird as the export genesis is following up on gen accounts, which we have created during gentx/collect-gentx(like we should have the state, shouldn't we?) and not explicitly looking into either the chain is started or not.

perhaps ideally? Something has to fill the initial state database, and if the chain is never started, then how is that supposed to occur? I'm still not sure why anyone would design for this case, as the genesis file is the most minimal and portable state at that height. As you've mentioned, exporting would be the same as copying and pasting the genesis file.

I've tried this with other binaries and the same panic happens, so while this exact case is not documented in the cosmos-sdk, I do not believe that is was created to support this case.

```
osmosisd export
panic: UnmarshalJSON cannot decode empty bytes

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get({{0x2601db8, 0xc00028f520}, 0xc0001fe018, {0x25a2630, 0xc00028f5f0}, {0x25a2680, 0xc00028f6f0}, {0xc00053e3c0, 0x4, 0x1a}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/x/params/types/subspace.go:109 +0x319
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.GetParamSet({{0x2601db8, 0xc00028f520}, 0xc0001fe018, {0x25a2630, 0xc00028f5f0}, {0x25a2680, 0xc00028f6f0}, {0xc00053e3c0, 0x4, 0x1a}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/x/params/types/subspace.go:222 +0x145
github.com/cosmos/cosmos-sdk/x/auth/keeper.AccountKeeper.GetParams(...)
	github.com/cosmos/cosmos-sdk@v0.44.5/x/auth/keeper/params.go:15
github.com/cosmos/cosmos-sdk/x/auth.ExportGenesis({{0x25d9f68, 0xc000128000}, {0x2606f60, 0xc00028d000}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.44.5/x/auth/genesis.go:32 +0x125
github.com/cosmos/cosmos-sdk/x/auth.AppModule.ExportGenesis({{}, {{0x25a2630, 0xc00028f580}, {0x2601db8, 0xc00028f520}, {{0x2601db8, 0xc00028f520}, 0xc0001fe018, {0x25a2630, 0xc00028f5f0}, ...}, ...}, ...}, ...)
```

**Comment by liamsi** [comment] 2022-05-18 13:46
The state DB gets only written into after the chain is started. Before that there is nothing to export as there is no state (besides the representation in the genesis file). Why don't you just copy around the genesis file?

**Comment by liamsi** [comment] 2022-05-18 14:06
I'm going to close this issue. 

The docs for `ExportGenesis` clearly explain what its use is (exporting the most recent state; mainly to be used for hard-forks s.t. they can use it as a new genesis). Similarly with the command (though the docs could be better here–which is not an app issue). If there is no app state there is nothing to export.

**Closed by liamsi** 2022-05-18 14:06 UTC
Labels: bug, help wanted, C: Celestia app
