### ISSUE TITLE
qgb: Add ability to query for validator set by nonce

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#278] opened 2022-04-07 13:42 UTC
In order for the relayer to easily submit validator set updates, we should add a query to fetch a specific validator set by nonce.

**Comment by SweeXordious** [comment] 2022-05-05 18:12
Closing. Duplicate of https://github.com/celestiaorg/celestia-app/issues/343

**Closed** 2022-05-05 18:12 UTC
Labels: duplicate, C: QGB
